### ISSUE TITLE
Styling issues with GitBook 1.0

### ISSUE THREAD

**Issue by citizenmatt** [rlmv/gitbook-plugin-anchors#2]
Can't see the link icon properly when you hover over a heading with GitBook 1.0. If you update the `plugin.css` `a.plugin-anchor` rule to have `padding-left: 40px` it works. I've no idea why :smile:

**Comment by rlmv** [comment]
Oops sorry y'all, I have not been on Github in a while and totally missed this. Yes, I am happy to merge this fix. I'll push a new version out ASAP.
