### ISSUE TITLE
hook 'page' is deprecated

### ISSUE THREAD

**Issue by piranna** [rlmv/gitbook-plugin-anchors#4]
By using gitbook 2.0.0, autocover raise the next error

```
hook 'page' used by plugin 'gitbook-plugin-anchors' is deprecated, and will be remove in the coming versions
```

This should be updated.

**Comment by wcandillon** [comment]
+1

**Comment by piranna** [comment]
Any update on this?

**Comment by zuoRambo** [comment]
+1 @rlmv please attention

**Comment by rlmv** [comment]
Hi @piranna @zuoRambo @wcandillon, I'm no longer using Gitbook so have not kept up with the Gitbook API. Can one of you send me a pull request? I'm happy to merge.

**Comment by zuoRambo** [comment]
@rlmv i study the source code of gitbook,find that after the version 0.7.1 gitbook deprecated many hooks 
```javascript
//line 33  lib\plugin.js
Plugin.HOOKS = [
    "init", "finish", "finish:before"
]

//line 158
if (!_.contains(Plugin.HOOKS, name)) this.book.log.warn.ln("hook '"+name+"' used by plugin '"+this.name+"' is deprecated, and will be removed in the coming versions");
```

**Comment by piranna** [comment]
And how we could fix it? What could be the alternative to 'page' hook?

**Comment by bbatsche** [comment]
Just to make things even worse, the hook may or may not **actually** be deprecated: GitbookIO/gitbook#684

**Comment by SamyPesse** [comment]
These hooks are no longer deprecated: https://github.com/GitbookIO/gitbook/commit/a4422593f20b9e410f13841cc20b8b9a1632eab0

**Comment by rlmv** [comment]
Looks like this is resolved. Thanks for the update @SamyPesse!
