### ISSUE TITLE
anchor jump not working

### ISSUE THREAD

**Issue by anibalsanchez** [rlmv/gitbook-plugin-anchors#5]
Hi,

We have updated to the latest gitbook version. Now, we have found that anchors are not working. 

For example, you visit the Url, it is defined, but browser does not jump.

To fix it, we have added jQuery and a script with [addcssjs](http://plugins.gitbook.com/plugin/addcssjs) plugin. In this way, location it forced to jump to the Url with anchor.

	var target = window.location.hash;
	
	window.location.hash = "";
	
	$(document).ready(function() {
		setTimeout(function() {
			document.location.hash = target;
		}, 50);
	});

**Comment by rlmv** [comment]
Is this still the case? The plugin works fine for me and I can't reproduce your bug with the latest Gitbook version.
