### ISSUE TITLE
gitbook-plugin-anchors is deprecated

### ISSUE THREAD

**Issue by romaindso** [rlmv/gitbook-plugin-anchors#6]
Hi,
Thank you for your plugin, it's great. 

But did you notice that it generates some warnings with Gitbook > 2.x.  :

`warn: hook 'page' used by plugin 'gitbook-plugin-anchors' is deprecated, and will be removed in the coming versions`

Do you have plan to support Gitbook 2 and superior ?
Thx

**Comment by rlmv** [comment]
Hi @romaindso, the 'page' hook is no longer deprecated. See the discussion at #4 . 

I think upgrading your Gitbook version will remove the warning.
