### ISSUE TITLE
Anchor icon font-size is overridden (too large)

### ISSUE THREAD

**Issue by harigopal** [rlmv/gitbook-plugin-anchors#8]
We're using Gitbook v2.6.5, and plugin version 0.5.0, and the anchor icon is too large.

![anchors plugin bug](https://cloud.githubusercontent.com/assets/98546/11839274/79c2049a-a412-11e5-912a-dd1101f64873.png)

The `font-size` property for the span appears to be overridden by higher specificity CSS from Gitbook itself.

I've hacked a fix for it by [including some extra CSS into our book](https://github.com/svlabs/playbook/commit/aaedab6134319d133fae30da631657cc70576ade):

```css
a.plugin-anchor span {
  font-size: 15px !important;
}
```

I'm not sure whether using `!important` is the right approach, but it works. :-/

**Comment by simov** [comment]
:+1: same issue here

**Comment by rlmv** [comment]
Ok, thanks for the report. I'll take a look at it!

**Comment by irazasyed** [comment]
Same issue!

**Comment by rlmv** [comment]
I've just published a new version (0.6.0) which fixes this issue. Cheers!
